logging:
  level:
    com.github.tanyueran: info
  file:
    path: /var/logs/mall-cake

spring:
  cloud:
    nacos:
      discovery:
        namespace: 8aab987e-15e5-404f-b27c-c12e6ebeefb4
        server-addr: 192.168.150.130