logging:
  level:
    com.github.tanyueran: debug

spring:
  cloud:
    alibaba:
      seata:
        tx-service-group: my_tx_group
    nacos:
      discovery:
        namespace: 8aab987e-15e5-404f-b27c-c12e6ebeefb4
        server-addr: 192.168.150.130:8848
  redis:
    host: 192.168.150.128
    port: 6379
    database: 1
    password: password
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.150.128:3306/cake-mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: password
#自定义的一些参数
self:
  key:
    private: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBALro/Ma8kGGZOzqhGgdW7N7kGM+sOFYJjHH4gNFKTsEQD2f+AHFUn3wUt4FJgayNwBvSY2t0lBw0W+vi5A2zChr1r3DEyxllASkyTj5usnoEW155ckPAwKOndH/ijTre87CdFH+Ahs/S2cCYoCGnNNDVhWCX3jlKMhJIZxjUL1KDAgMBAAECgYBwT5e0g5HuU3j3nd5aEq16sW0HPOENMeemhEBDgncYI2Jeho4Vi1fZ40jw8w5sdTC+hwkehIqK+BtT/p4ybSbgTRQPfYI4PlL818ezKV7AeIOWBGXMFvY99C4HlrIsZm8hvtvEqynUV05BpvPd9vn/HaBmMhumylHFmhTNH5RBgQJBAOXg0aCHj6V6TWacu7sgw2kIeYN1KygLwWd6AbKkl1VU0RxZWYsP32HA1nQiXmH1U15rS0lxxs7o/R4qD+XOvvECQQDQJjjjMW22nNzRW8kPCRTSD1JvD1+Ae4qGoP3vdjSNeNr9y73FhlYUj8Swtz/idnJqmPqwXXauZ2Bx3Hb5PNCzAkEAkpGn1wzYIBA87aIdaJDZR0zp/VFltODZ7doy3u5mtzefJM4rc6kpKrDDi8SmHRtIjrkmhauPsTmIugTjogkSYQJAKwkcDe00T+NSzH57rX4lLeE5G/lDt57TX0598jqwVue772lmjSZfOdUXx6m7rajrsxp6CmjoltqM2D3K43EtfQJAFl5KElhPVqENLV2w8vxxoIn98DIyqA6yIL8Iq2Kdqgkr/2O2GA0HI6vU8T2Dxi8dKLnCmF8JxIMNSVyl3cK3zw==
    public: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC66PzGvJBhmTs6oRoHVuze5BjPrDhWCYxx+IDRSk7BEA9n/gBxVJ98FLeBSYGsjcAb0mNrdJQcNFvr4uQNswoa9a9wxMsZZQEpMk4+brJ6BFteeXJDwMCjp3R/4o063vOwnRR/gIbP0tnAmKAhpzTQ1YVgl945SjISSGcY1C9SgwIDAQAB